# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

# Put your Papertrail & Loggly config here
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: PAPERTRAIL_PROTOCOL
      valueFrom:
        secretKeyRef:
          name: logging-secret
          key: PAPERTRAIL_PROTOCOL
    - name: PAPERTRAIL_HOST
      valueFrom:
        secretKeyRef:
          name: logging-secret
          key: PAPERTRAIL_HOST
    - name: PAPERTRAIL_PORT
      valueFrom:
        secretKeyRef:
          name: logging-secret
          key: PAPERTRAIL_PORT
    - name: LOGGLY_TOKEN
      valueFrom:
        secretKeyRef:
          name: logging-secret
          key: LOGGLY_TOKEN
    - name: TAGS
      value: "K8S-GL"

