# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rkubelog"
  namespace: "default"
  labels:
    app: rkubelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkubelog
  template:
    metadata:
      labels:
        kail.ignore: "true"
        app: rkubelog
    spec:
      serviceAccountName: rkubelog-sa
      containers:
      - image: public.ecr.aws/m4a9o5c3/rkubelog:ec16aa26b1a16889970dc54b860d369522f3e5be
        imagePullPolicy: Always
        name: "rkubelog"
        command:
        - /app/rkubelog
