# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

name: Build Release Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: "rkubelog"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker build & push
        run: |
          DOCKER_BUILDKIT=1 docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --no-cache --push -t public.ecr.aws/m4a9o5c3/${{ env.IMAGE_NAME }}:${{ github.sha }} -t public.ecr.aws/m4a9o5c3/${{ env.IMAGE_NAME }}:latest .
